# Generated by Django 6.0.6 on 2026-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('meal', 'Meal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='1', help_text='Separate ingredients with commas'),
            preserve_default=False,
        ),
    ]
