# Generated by Django 6.0.6 on 2026-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_food_category_food_food_type_food_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('meal', 'Meal')], default='meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='', help_text='Separate ingredients with commas'),
        ),
    ]
